project:
  type: website
  output-dir: docs

website:
  title: "Byte Sized ML"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/haadkhan
      - icon: linkedin
        href: https://linkedin.com/in/haadkhan
  body-footer: |
      <!-- 100% privacy-first analytics -->
      <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
      <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>

format:
  html:
    theme: sandstone
    css: styles.css
