---
title: "Building Blocks of Transformers: 1. Self Attention"
format:
  html:
    code-fold: true
jupyter: python3
author: "Haad Khan"
date: "2023-10-01"
categories: [Attention, Transformers, Machine Learning]
---

<p>I had a garbled understanding of Transformer architecture after consulting blogs, videos and coursera course. What made it finally clicked for me is Stanford CS 224N lecture by John Hewitt. He does a phenomenal job and I will strongly encourage to check it out. If you work with LLM's the 1 hour and 17 minutes is worth the time investment.</p> 
[Stanford CS224N NLP | Lecture 8 - Self-Attention and Transformers](https://youtu.be/nTQUwghvy5Q)
<p>Before diving into the details of transformer a little history.<br>

### Motivation for Attention

Prior to introduction of Transformers, the state of the art algorithm for acheiving state of the art results on various NLP tasks were RNN's and its variants e.g LSTM, BiDirectional LSTM etc.

While the sequential nature of RNN lend itself well to modelling sequential data, it had some issues.
Linear interaction distance
Lack of parallelizability


</p>


```{python}
# | label: Attention Implementation
import torch
import torch.nn as nn
import torch.nn.functional as F


class ScaledDotProductAttention(nn.Module):
    """Scaled Dot-Product Attention"""

    def __init__(self, temperature, attn_dropout=0.1):
        super().__init__()
        self.temperature = temperature
        self.dropout = nn.Dropout(attn_dropout)

    def forward(self, q, k, v, mask=None):

        attn = torch.matmul(q / self.temperature, k.transpose(2, 3))

        if mask is not None:
            attn = attn.masked_fill(mask == 0, -1e9)

        attn = self.dropout(F.softmax(attn, dim=-1))
        output = torch.matmul(attn, v)

        return output, attn


```